version: "3.8"
services:
  test:
    image: manaphp/php80:latest
    volumes:
      - ./:/var/www/html
      - ./etc/php/php.ini:/etc/php/php.ini
      - ./etc/php/fpm.conf:/etc/php/fpm.conf
      - ./cron.d:/tmp/cron.d
    environment:
      - APP_CRON_ENABLED=1
      #network_mode: host
    command: php /var/www/html/index.php
